name: art_grade
version: 1.0.0+1
publish_to: none
description: Art Grade
environment: 
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_riverpod: ^2.4.5
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.8
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  pinput: ^3.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  fonts:
    - family: lipighor
      fonts:
        - asset: assets/font/LiRegular.ttf
          weight: 400
          style: normal
        - asset: assets/font/LiItalic.ttf
          weight: 400
          style: italic
